language: node_js
sudo: required
services:
  - docker

before_install:
  - docker buld -t vbulnes/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vbulnes/docker-react npm run test
